#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
int sPos;											//variable for servo position

task main()
{
	while(true){
if (abs(joystick.joy1_y1) > 10) {				//Left stick makes robot drive forward at power level based on left stick postion
																				//Power is divided by 4 so 128/4 = 32 Max Power, and -32 Min Power
				motor[Left] = joystick.joy1_y1/4;
				motor[Right] = joystick.joy1_y1/4;
			}
		}
		if (abs(joystick.joy1_x2) > 10) {
				motor[Right] =  joystick.joy1_x2/4;
				motor[Left] = -joystick.joy1_x2/4;
			}
		}
		if ((abs(joystick.joy1_y1) <= 10) && (abs(joystick.joy1_x2) <= 10)) {		//dead zone programed for both right and left sticks
			motor[Left] = 0;
			motor[Right] = 0;

		}
		if (joy1Btn(1) == 1 )			//Moves the servo arm up
  {
  	sPos = sPos + 5;
  	wait1Msec(25);
  	servo[servo1] = sPos;
  }
  if (joy1Btn(3) == 1 )		//Moves the servo arm down
  {
  	sPos = sPos - 5;
  	wait1Msec(25);
  	servo[servo1] = sPos;
  }
  if (sPos < 0)	//Limit: Will not assign a negative value to the servo
  {
  	sPos = 0;
  }
  if (sPos > 250) //Limit: will not extend past upper limit.
  								//Theoretical upper limit is 255 but may cause servo to burn out if held for extended periods
  {
  	sPos = 250;
	}
}
}
