#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
int sPos;

task main()
{
	while(true){
if (abs(joystick.joy1_y1) > 10) {
			if(joy1Btn(5) == 1){
				motor[Left] = joystick.joy1_y1/4;
				motor[Right] = joystick.joy1_y1/4;
			} else {
				motor[Left] = joystick.joy1_y1/4;
				motor[Right] = joystick.joy1_y1/4;
			}
		}
		if (abs(joystick.joy1_x2) > 10) {
			if(joy1Btn(5) == 1){
				motor[Right] = joystick.joy1_x2/4;
				motor[Left] = -joystick.joy1_x2/4;
			}else{
				motor[Right] =  joystick.joy1_x2/4;
				motor[Left] = -joystick.joy1_x2/4;
			}
		}
		if ((abs(joystick.joy1_y1) <= 10) && (abs(joystick.joy1_x2) <= 10)) {
			motor[Left] = 0;
			motor[Right] = 0;

		}
		if (joy1Btn(1) == 1 )
  {
  	sPos = sPos + 5;
  	wait1Msec(25);
  	servo[servo1] = sPos;
  }
  if (joy1Btn(3) == 1 )
  {
  	sPos = sPos - 5;
  	wait1Msec(25);
  	servo[servo1] = sPos;
  }
  if (sPos < 0)
  {
  	sPos = 0;
  }
  if (sPos > 250)
  {
  	sPos = 250;
	}
}
}
