
#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     eStopSwitch,    sensorTouch)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task emergencyStop()
{
	while(SensorValue(eStopSwitch) == 0)
	{
		wait1Msec(10);
	}
	StopAllTasks();
}

task main()
{
	StartTask(emergencyStop);

	while(true)
	{
		if(SensorValue(sonar) > 20)
		{
			motor[rightMotor] = 50;
			motor[leftMotor] 	= 50;
		}
		else
		{
			motor[leftMotor] 	= -30;
			motor[rightMotor] = -30;
			wait1Msec(5000);

			motor[leftMotor]	= -30;
			motor[rightMotor]	= 30;
			wait1Msec(2000);
		}
		wait1Msec(10);
	}
}
