#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     eStopSwitch,    sensorTouch)
#pragma config(Sensor, S3,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#Pragma statements must be in main file not #pragma Statements

#include "CalMove.c"
//CalMove.c contains calibrated movement for the robot in fuctions: moveForward, rightTurn, and leftTurn
#include "eStop.c"
//eStop.c contains simple e[mergency stop task with slight delay to processing overhead
#include "FigureEight.c"


task main()		//Starts first task, task main()
{
	StartTask(FigureEight);
	StartTask (emergencyStop); 	//Starts second task emergencyStop
	while(true){
	if(SensorValue[sonar] <= 30){
		stoptask(FigureEight);
		motor[motorD] = 0;
		motor[motorE] = 0;
		wait1Msec(200);
		rightTurn();
		wait1Msec(100);
		rightTurn();
		wait1Msec(100);
		moveForward(30);
		motor[motorD] = 0;
		motor[motorE] = 0;
		wait1Msec(200);
		StartTask(FigureEight);
	}
	wait1Msec(10);


	}
}
